### ISSUE TITLE
Bind already existing object

### ISSUE THREAD

**Issue by KatekovAnton** [davidsiaw/luacppinterface#22]
Is there any way to bind already existed object to the Lua instance? for example 

`lua.GetGlobalEnvironment().Set("context", this);`

**Comment by d3v1l401** [comment]
You have to catch the Lua Machine, which is not exposed in any way if not from your code itself.

**Comment by davidsiaw** [comment]
What are you trying to do, exactly? Can I see more code?

**Comment by davidsiaw** [comment]
This issue has been open for a while without replies, so I will hazard a guess to what you might be trying to do.

It is possible to pass ownership of an object to Lua by calling `lua.CreateUserdata<TypeName>(this)`. You can also pass it to Lua without passing ownership by calling `lua.CreateLightUserdata<TypeName>(this)`.

Otherwise just reopen the issue if LuaCppInterface does not do something you want
